name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - master

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 10
      - uses: actions/setup-node@v2
        with:
          node-version: 18
      - name: Copy Env Variables
        env:
          SPINBOARD_BASE_URL: ${{ env.SPINBOARD_BASE_URL }}
        run: |
          sed -i -e 's/{SPINBOARD_BASE_URL}/${{ env.SPINBOARD_BASE_URL }}/g' src/environments/environment.ts
          cat src/environments/environment.ts
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_HAPPY_OCEAN_0A3DE8E10 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/" # App source code path
          api_location: "" # Api source code path - optional
          output_location: "dist/spinboard-frontend" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######
